### ISSUE TITLE
Why is there a gap between ckbAvailable from getL1State and the value from ccc.getBalance()

### ISSUE THREAD

**Issue by sfsf332** [ickb/v1-interface#2]
![image](https://github.com/user-attachments/assets/e2263290-2fa2-4a45-a2e1-cf2a17f23bb0)
 in my wallet and ccc.getBalance()  the value is 68980.2194604

**Comment by phroi** [comment]
Hey @sfsf332, thank you for publicly expressing your interest in iCKB as part of the integration of iCKB in NervDAO, I personally appreciate a lot!! 🙏  Also thank you for the question, also [ducati.bit was affected by it](https://t.me/NervosNation/307406/320525), but I completely forgot to address this detail until now.

For starters I'd like to point out that `ccc.getBalance()` is **not part of my codebase**, so I don't know what you are talking about. Please, keep that in mind :monocle_face:

Talking about what is in my codebase, we have `ckbBalance` and `ckbAvailable`. Fell free to check out: https://github.com/ickb/v1-interface/blob/7f474a6ce6bc1f7a46f4ea26bb2b72d705b7b733/src/queries.ts#L164-L171

 - `ckbBalance` is the sum of all CKB controlled directly or **indirectly** by the wallet account.
 - `ckbAvailable` is `ckbBalance` minus the the CKB locked in Withdrawal requests not yet mature and minus `1000 CKB`

**Why are these 1000 CKB reserved in the v1-interface?**

The v1-interface doesn't allow users to convert these 1000 CKB to iCKB because the there are a lot of state transitions that require a sizable amount of CKB to work due to the creation of new cells.

If you [take a quick look at the proposal](https://github.com/ickb/proposal) you'll realize that many actions require a safe buffer of CKB to work:
- [Order Mint](https://github.com/ickb/proposal#mint-owned-owner)
- [Depost Phase 1](https://github.com/ickb/proposal#deposit-phase-1)
- [Withdrawal Phase 1](https://github.com/ickb/proposal#mint-owned-owner)

It could be documented better, sure. @sfsf332 does all this makes sense to you?

Love & Peace, Phroi

**Comment by sfsf332** [comment]
Thanks,that's helpful

**Comment by phroi** [comment]
Closing for now, feel free to reopen it if you have any other doubts :hugs:
